version: "3"
services:

  ldap:
    image: osixia/openldap:1.2.0
    container_name: keycloak-ldap
    ports:
      - 389:389
      - 636:636
    networks:
      - keycloak

  ldapadmin:
    image: osixia/phpldapadmin:0.7.1
    container_name: keycloak-ldapadmin
    ports:
      - 8280:80
      - 6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
    networks:
      - keycloak
    links:
      - ldap

  postgres:
    image: postgres:9.6
    container_name: keycloak-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=123456
    networks:
      - keycloak

  keycloak:
    image: jboss/keycloak
    container_name: keycloak-server
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: 123456
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8180:8080
    depends_on:
      - postgres
    networks:
      - keycloak
    
networks:
  keycloak: